### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by TommieNL** [JasperMC/MarktplaatsScraper#2]
Hi Jasper,

I was able to start MarktplaatsScraper in docker via docker-MarktplaatsScraper. 

I've configured the token, id, config dir and a test MP search. And I see results appearing in `/config/Listings`

But 'm not receiving notifications (yet). 

I noted that the config.json in `/config`  contained default settings, should i edit these? I did set them (the API and user KEY) in docker-compose.yaml so they will be probably available as environment variables?

Is there a way to troubleshoot / see communication logging when communicating with Pushover? 

Greets JT

**Comment by TommieNL** [comment]
hmm wait.. i'm seeing stats in the pushover web GUI.. probably an issue with my device config...

**Comment by TommieNL** [comment]
I'm not sure what did the trick (editing config.json and restarting or registering my device again with Pushover) 

But it's working now!

**Comment by JasperMC** [comment]
I noticed I had some trouble as well yesterday. Maybe Pushover itself?

If you're using docker-MarktplaatsScraper, the logic of the program first looks if there are command line arguments (e.g. the Docker environment variables for the API key and user key) and if not, it loads config.json.

In the dockerfile in this specific repository, the environment variables don't get passed through, so config.json is preferred.
